# WhatATheme
markdown: kramdown

# URL of the Site
url: 'https://xenoscube.ai'
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: ""

# Title of the Site
title: "Xenoscube"
# Description of the Site
description: "Where Superintelligence Begins"
# URL of Image of the Site
site-image: /assets/images/xenoscube-logo_black.png
# Keywords of the Site
site-keywords: xenoscube, ai infra, ai supercomputer, npu
# URL for the Image of custom Favicon
favicon-url: /assets/images/xenoscube-favicon-bg.png

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
# heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940
heroimage: /assets/images/cube-in-space.png

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: contact@xenoscube.ai
facebook_username:
twitter_username:
instagram_username:
linkedin_username: xenoscube
github_username: xenoscube
youtube_channel_id:
reddit_username:
behance_username:
dribbble_username:
spotify_username:

# Google Analytics
google-analytics: 

# Disqus
disqus-shortname: 

# Name of the Author
author-name: Xenoscube
# URL for the Image of the Author
#author-image: https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png
author-image: /assets/images/xenoscube-logo_black.png
author-imagewhite: /assets/images/xenoscube-logo_white.png
# 60 Words About the Author
author-about: Xenoscube is a startup company that specializes in AI infrastructure and supercomputing. We are dedicated to building the world's most advanced AI supercomputer, which will enable the development of superintelligent systems. Our mission is to push the boundaries of AI technology and create a future where superintelligence is a reality. 
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/xenoscube

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
